version: "3"

services:
    slack-moderation:
        build: .
        volumes:
            - .:/moderation
            - ./src/assets:/moderation/src/assets
        command: './run_django.sh'
        restart: always
        stdin_open: true
        tty: true
        logging:
            options:
                max-size: 4096m

    nginx:
        build: ./nginx
        volumes:
            - ./src/assets:/moderation/src/assets
        depends_on:
            - slack-moderation
        restart: always
        stdin_open: true
        tty: true
        logging:
            options:
                max-size: 4096m
volumes:
    pg-data:
