version: "3"

services:
    slack-moderation:
        env_file:
            - ./.env
        environment:
          - ENVIRONMENT=Production
          - POSTGRES_HOST=${POSTGRES_HOST}
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - run:/moderation/src/run

    nginx:
        ports:
            - 80:80
            - 443:443
        volumes: 
          - nginx-certs:/etc/nginx/certs
          - run:/moderation/src/run
        env_file:
          - ./.env
volumes:
  nginx-certs:
  run:
