version: "3"

services:
    slack-moderation:
        volumes:
            - run:/moderation/src/run

    nginx:
        ports:
            - 80:80
            - 443:443
        volumes:
          - nginx-certs:/etc/nginx/certs
          - run:/moderation/src/run
volumes:
  nginx-certs:
  run:
