version: "3"

services:
    postgres:
        image: postgres:16-alpine
        ports:
            - "5433:5433"
        volumes:
            - pg-data:/var/lib/postgresql/data
        command: -p 5433

    slack-moderation:
        expose:
            - 8000
        depends_on:
            - postgres

    nginx:
        ports:
            - 8000:80
