version: "3"

services:
    slack-moderation:
        build: .
        volumes:
            - .:/moderation
            - ./src/assets:/moderation/src/assets
        command: './run_django.sh'
        restart: always
        stdin_open: true
        tty: true
        logging:
            options:
                max-size: 4096m
        env_file:
            - ./.env

    nginx:
        build: ./nginx
        volumes:
            - ./src/assets:/moderation/src/assets
        depends_on:
            - slack-moderation
        restart: always
        stdin_open: true
        tty: true
        logging:
            options:
                max-size: 4096m
        env_file:
            - ./.env

    rabbit:
        image: rabbitmq:3.13-alpine
        restart: always
        logging:
            options:
                max-size: 4096m

    celery_worker:
        build: .
        command: './run_celery_worker.sh'
        restart: always
        depends_on:
            - slack-moderation
        logging:
            options:
                max-size: 4096m
        env_file:
            - ./.env
volumes:
    pg-data:
