# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderation',
            name='last_action_author_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderation',
            name='tls',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moderationaction',
            name='action_author_id',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
