# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderation',
            name='content_key',
            field=models.TextField(),
        ),
    ]
