# Generated by Django 2.1.15 on 2022-02-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0002_auto_20161215_0303'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='moderation',
            index=models.Index(fields=['content_key'], name='moderations_content_1a0145_idx'),
        ),
        migrations.AddIndex(
            model_name='moderation',
            index=models.Index(fields=['content'], name='moderations_content_704c1a_idx'),
        ),
        migrations.AddIndex(
            model_name='moderation',
            index=models.Index(fields=['content_author_id'], name='moderations_content_d116ed_idx'),
        ),
        migrations.AddIndex(
            model_name='moderation',
            index=models.Index(fields=['created_at'], name='moderations_created_7adaf6_idx'),
        ),
        migrations.AddIndex(
            model_name='moderation',
            index=models.Index(fields=['status'], name='moderations_status_035820_idx'),
        ),
        migrations.AddIndex(
            model_name='moderation',
            index=models.Index(fields=['status_reason'], name='moderations_status__ba5626_idx'),
        ),
        migrations.AddIndex(
            model_name='moderation',
            index=models.Index(fields=['status_date'], name='moderations_status__e0f2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='moderation',
            index=models.Index(fields=['message_id'], name='moderations_message_da4c7e_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['moderation'], name='moderations_moderat_3f2391_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['action'], name='moderations_action_9f5e79_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['action_author_id'], name='moderations_action__4b3150_idx'),
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['created_at'], name='moderations_created_c0bf25_idx'),
        ),
    ]
