# Generated by Django 4.0.5 on 2022-06-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0003_moderation_moderations_content_1a0145_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='moderation',
            name='moderations_content_704c1a_idx',
        ),
    ]
