# Generated by Django 4.0.5 on 2022-06-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0004_remove_moderation_moderations_content_704c1a_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='moderation',
            name='moderations_content_1a0145_idx',
        ),
    ]
