# Generated by Django 5.1.1 on 2024-09-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("moderations", "0005_moderation_was_new_user_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderation",
            name="content_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("answer", "answer"),
                    ("question", "question"),
                    ("comment", "comment"),
                    ("thankyoucomment", "thankyoucomment"),
                    ("profileanswer", "profileanswer"),
                    ("answerstep", "answerstep"),
                    ("todolist", "todolist"),
                    ("todo", "todo"),
                    ("careergoalstatement", "careergoalstatement"),
                    ("profileimage", "profileimage"),
                    ("questiontag", "questiontag"),
                    ("useraboutprofile", "useraboutprofile"),
                ],
                db_comment="Indicated the type of content from a predefined list of types.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="moderation",
            name="was_new_user_content",
            field=models.BooleanField(
                db_comment="Indicates if the content was from a new user and needs pre-approval before showing it.",
                default=False,
            ),
        ),
    ]
