# Generated by Django 4.0.5 on 2022-06-16 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0005_remove_moderation_moderations_content_1a0145_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='moderationaction',
            name='moderations_moderat_3f2391_idx',
        ),
    ]
