# Generated by Django 4.0.5 on 2022-06-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderations', '0006_remove_moderationaction_moderations_moderat_3f2391_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='moderation',
            name='moderations_content_d116ed_idx',
        ),
        migrations.AddIndex(
            model_name='moderationaction',
            index=models.Index(fields=['moderation'], name='moderations_moderat_3f2391_idx'),
        ),
    ]
