import os

MOD_FLAGGED_CHANNEL_ID = os.environ.get("MOD_FLAGGED_CHANNEL_ID")
APPROVED_ADVICE_CHANNEL_ID = os.environ.get("APPROVED_ADVICE_CHANNEL_ID")
BEST_OF_VILLAGE_CHANNEL_ID = os.environ.get("BEST_OF_VILLAGE_CHANNEL_ID")
COACHING_CHANNEL_ID = os.environ.get("COACHING_CHANNEL_ID")
MOD_APPROVED_CHANNEL_ID = os.environ.get("MOD_APPROVED_CHANNEL_ID")
MOD_INBOX_CHANNEL_ID = os.environ.get("MOD_INBOX_CHANNEL_ID")
MOD_LEADERBOARD_CHANNEL_ID = os.environ.get("MOD_LEADERBOARD_CHANNEL_ID")
MOD_RESOLVED_CHANNEL_ID = os.environ.get("MOD_RESOLVED_CHANNEL_ID")
MOD_SUSPECTED_AI_CHANNEL_ID = os.environ.get("MOD_SUSPECTED_AI_CHANNEL_ID")
NEW_USER_CONTENT_CHANNEL_ID = os.environ.get("NEW_USER_CONTENT_CHANNEL_ID")
QUALITY_ASSESSED_CHANNEL_ID = os.environ.get("QUALITY_ASSESSED_CHANNEL_ID")

# Channel IDs dictionary, used to get channel IDs by channel name
CHANNEL_IDS_DICT = {
    "mod-flagged": MOD_FLAGGED_CHANNEL_ID,
    "approved-advice": APPROVED_ADVICE_CHANNEL_ID,
    "best-of-village": BEST_OF_VILLAGE_CHANNEL_ID,
    "coaching": COACHING_CHANNEL_ID,
    "mod-approved": MOD_APPROVED_CHANNEL_ID,
    "mod-inbox": MOD_INBOX_CHANNEL_ID,
    "mod-leaderboard": MOD_LEADERBOARD_CHANNEL_ID,
    "mod-resolved": MOD_RESOLVED_CHANNEL_ID,
    "mod-suspected-ai": MOD_SUSPECTED_AI_CHANNEL_ID,
    "new-user-content": NEW_USER_CONTENT_CHANNEL_ID,
    "quality-assessed": QUALITY_ASSESSED_CHANNEL_ID,
}
