# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.TextField()),
                ('service_entity_auth_name', models.TextField()),
                ('service_entity_auth_id', models.TextField()),
                ('service_auth_token', models.TextField()),
                ('username', models.CharField(max_length=50)),
            ],
        ),
    ]
