# Generated by Django 2.1.15 on 2022-02-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['service_name'], name='accounts_au_service_753737_idx'),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['service_entity_auth_name'], name='accounts_au_service_21702b_idx'),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['service_entity_auth_id'], name='accounts_au_service_71c0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['service_auth_token'], name='accounts_au_service_1097ea_idx'),
        ),
        migrations.AddIndex(
            model_name='authtoken',
            index=models.Index(fields=['username'], name='accounts_au_usernam_227e5e_idx'),
        ),
    ]
