server {
    listen 80;
    server_name slack-moderation.com;

    # gzip
    gzip             on;
    gzip_min_length  1000;
    gzip_proxied     any;
    gzip_types       text/css image/png image/jpeg image/jpg application/x-javascript;
    gzip_disable     "MSIE [1-6]\.";

    # Logs
    access_log logs/moderation_nginx_cv_access.log;
    error_log logs/moderation_nginx_cv_error.log;

    # Health check for AWS ALB
    location /health {
        access_log off; # Prevents logs from filling up with health checks
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    location / {
        proxy_set_header X-Forwarded-Proto https;
        uwsgi_param UWSGI_SCHEME https;
        uwsgi_pass_header X_FORWARDED_PROTO;
        uwsgi_pass unix:/moderation/src/run/moderation.sock;
        include /etc/nginx/uwsgi_params;
    }

    location /static/ {
        alias /moderation/src/assets/;
    }

    location /moderations/moderations {
        proxy_set_header X-Forwarded-Proto https;
        uwsgi_param UWSGI_SCHEME https;
        uwsgi_pass_header X_FORWARDED_PROTO;
        uwsgi_pass unix:/moderation/src/run/moderation.sock;
        include /etc/nginx/uwsgi_params;
    }
}
